import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import personnelApi from '../api/personnel.api.js';

export const usePersonnel = () => {
  return useQuery({
    queryKey: ['personnel'],
    queryFn: () => personnelApi.getPersonnel()
  });
};

export const usePersonnelById = (id) => {
  return useQuery({
    queryKey: ['personnel', id],
    queryFn: () => personnelApi.getPersonnelById(id),
    enabled: Boolean(id)
  });
};

export const useMyOrganization = () => {
  return useQuery({
    queryKey: ['organization', 'me'],
    queryFn: () => personnelApi.getMyOrganization()
  });
};

export const useCreatePersonnel = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data) => personnelApi.createPersonnel(data),
    onSuccess: (res) => {
      queryClient.invalidateQueries({ queryKey: ['personnel'] });
      queryClient.invalidateQueries({ queryKey: ['employees'] });
      queryClient.invalidateQueries({ queryKey: ['organization', 'me'] });
      
      const createdUser = res.user;
      const pwd = res.autoGeneratedPassword;
      if (pwd) {
        toast.success(
          `Personnel account '${createdUser.email}' created. Generated Password: ${pwd}`,
          { duration: 10000 }
        );
      } else {
        toast.success(`Personnel account '${createdUser.email}' created successfully.`);
      }
    },
    onError: (err) => {
      toast.error(err.response?.data?.message || 'Failed to create personnel account');
    }
  });
};

export const useUpdatePersonnel = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }) => personnelApi.updatePersonnel(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['personnel'] });
      queryClient.invalidateQueries({ queryKey: ['employees'] });
      queryClient.invalidateQueries({ queryKey: ['organization', 'me'] });
      toast.success('Personnel record updated successfully');
    },
    onError: (err) => {
      toast.error(err.response?.data?.message || 'Failed to update personnel record');
    }
  });
};

export const useDeletePersonnel = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id) => personnelApi.deletePersonnel(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['personnel'] });
      queryClient.invalidateQueries({ queryKey: ['employees'] });
      queryClient.invalidateQueries({ queryKey: ['organization', 'me'] });
      toast.success('Personnel account removed');
    },
    onError: (err) => {
      toast.error(err.response?.data?.message || 'Failed to delete personnel account');
    }
  });
};

export default {
  usePersonnel,
  usePersonnelById,
  useMyOrganization,
  useCreatePersonnel,
  useUpdatePersonnel,
  useDeletePersonnel
};
